# Generated by Django 2.0.3 on 2018-03-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180330_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='thumb',
            new_name='image',
        ),
    ]
